services:
  - type: web
    name: mutantes-api
    env: java
    buildCommand: ./gradlew build -x test
    startCommand: java -jar build/libs/inicial1-0.0.1-SNAPSHOT.jar
    healthCheckPath: /stats
    envVars:
      - key: SERVER_PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
